on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x86, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        id: set_up_python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: ${{ matrix.architecture }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate binary exe file
        run: |
          pip install pyinstaller
          pyinstaller --onefile --noconsole --add-data 'translation/*.qm;translation/' SportiduinoPQ.py
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: SportiduinoPQ-${{ steps.get_version.outputs.VERSION }}-win-${{ matrix.architecture }}
          path: dist/SportiduinoPQ.exe
      #- name: Create Release
      #  id: create_release
      #  uses: actions/create-release@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    tag_name: ${{ github.ref }}
      #    release_name: Release ${{ github.ref }}
      #    draft: false
      #    prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/sembruk/SportiduinoPQ/releases/${{ steps.get_version.outputs.VERSION }}/assets
          asset_path: dist/SportiduinoPQ.exe
          asset_name: SportiduinoPQ-${{ steps.get_version.outputs.VERSION }}-win-${{ matrix.architecture }}
          asset_content_type: application/octet-stream


# vim: ts=2 sw=2 et
