name: Build

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x86, x64]
    name: Build on Windows ${{ matrix.architecture }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        id: set_up_python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: ${{ matrix.architecture }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate binary exe file
        run: |
          pip install pyinstaller
          pyinstaller --onefile --noconsole --add-data 'translation/*.qm;translation/' SportiduinoPQ.py
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - name: Rename artifacts
        run: |
          mv dist/SportiduinoPQ.exe dist/SportiduinoPQ-${{ steps.get_version.outputs.VERSION }}-win-${{ matrix.architecture }}.exe
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          #name: SportiduinoPQ-${{ steps.get_version.outputs.VERSION }}-win-${{ matrix.architecture }}
          path: dist/*.exe
      - name: Generate Changelog
        run: |
          # Get text after ## ... <version> from changelog.ru.md and changelog.en.md
          sed -n "/^##.*${{ github.ref_name }}.*$/,/^##/{/^##/d ; p}" CHANGELOG.ru.md | sed -z "s/^\n*//g" - > ${{ github.workspace }}-CHANGELOG.txt
          printf "\n---\n" >> ${{ github.workspace }}-CHANGELOG.txt
          sed -n "/^##.*${{ github.ref_name }}.*$/,/^##/{/^##/d ; p}" CHANGELOG.md | sed -z "s/^\n*//g" - >> ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: |
            dist/*.exe

# vim: ts=2 sw=2 et
